# Stage 1
FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN npm install --frozen-lockfile
COPY . .
RUN npm run build

# Stage 2
FROM node:20-alpine AS runner
WORKDIR /app
RUN npm install -g pnpm
COPY --from=builder /app ./
EXPOSE 10000
CMD ["npm", "run", "start"]