FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package*.json ./
COPY prisma ./prisma       

RUN pnpm install           

COPY . .                   

RUN pnpm run build

EXPOSE 10001

CMD ["node", "dist/index.js"]
