FROM postgres:18.1

RUN apt-get update && apt-get install -y \
    postgresql-18-cron \
    postgresql-18-tds-fdw \
    freetds-dev \
    && rm -rf /var/lib/apt/lists/*

# เพิ่มการตั้งค่า shared_preload_libraries เพื่อให้ pg_cron ทำงานได้
# (tds_fdw ไม่ต้องใส่ใน preload libraries)
RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample

# หากต้องการระบุให้ pg_cron รันเฉพาะใน DB ที่กำหนด (ทางเลือก)
# RUN echo "cron.database_name = 'your_db_name'" >> /usr/share/postgresql/postgresql.conf.sample

# คำสั่ง Build และ Run (เหมือนเดิม)
# docker build -f Dockerfile.pgcron -t vms-db .
# docker run --name pg-container -p 2405:5432 -e POSTGRES_PASSWORD=123456 -d vms-db
# CREATE EXTENSION IF NOT EXISTS tds_fdw;
# CREATE EXTENSION IF NOT EXISTS pg_cron;
EXPOSE 10002

# Override postgres to listen on port 10002
CMD ["postgres", "-p", "10002"]